#!/usr/bin/env bash
# Transfer file from the client to a server
if [ $# -ge 4 ]; then
    scp "$1" "$3"@"$2":'~/' -i "$4"
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
