#!/usr/bin/env bash
# Install ngnix and initial config
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
ufw allow 80
ufw allow 22
echo "Hello World!" | tee /var/www/html/index.html
nginx -t
service nginx restart
