#!/usr/bin/env bash
# Redirection page
echo "server {
    listen 80;
    listen [::]:80;

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        #return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        return 301 https://www.google.com;
    }
}" | sudo tee /etc/nginx/sites-available/redirect
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/
sudo nginx -t
sudo service nginx reload
