#!/usr/bin/env bash
# Redirection page
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
ufw allow 80
ufw allow 22
echo "Hello World!" | tee /var/www/html/index.html
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bu
sed -i 's/server_name _;/server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}/g' /etc/nginx/sites-available/default
nginx -t
service nginx reload
