#!/usr/bin/env bash
# Install ngnix and initial config
apt-get -y update
apt-get -y install nginx
apt-get -y install ufw
echo 'y' | ufw enable
ufw allow 'Nginx HTTP'
ufw allow 80
ufw allow 22
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/404.html
echo -e "Ceci n'est pas une page\n" > /var/www/html/404.html
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bu
sed -i 's/server_name _;/server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n/g' /etc/nginx/sites-available/default
sed -i 's/server_name _;/server_name _;\n\n\terror_page 404 \/404.html;\n\n\tlocation = \/404.html {\n\t\tinternal;\n\t}\n/g' /etc/nginx/sites-available/default
sed -i 's/server_name _;/server_name _;\n\n\tadd_header X-Served-By $hostname;\n/g' /etc/nginx/sites-available/default
nginx -t
service nginx restart
